### ISSUE TITLE
De-board Eric Loos from PC

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/productcom#1]
[x] remove from productcom mailing list
[x] close peeringdb.com email address
[x] remove from peeringdb slack
[x] remove from productcom page in docs.peeringdb.com
[x] redistribute assigned issues
[x] remove from productcom page in PDB deck
[x] Remove from peeringdb github team
[ ] award plaque sent

**Comment by ccaputo** [comment]
[x] remove from productcom mailing list
[x] close peeringdb.com email address
[x] remove from productcom page in docs.peeringdb.com

**Comment by ccaputo** [comment]
[x] Remove from peeringdb github team

**Comment by job** [comment]
[x] remove from peeringdb slack

**Comment by ghankins** [comment]
[x] remove from productcom page in PDB deck
