### ISSUE TITLE
Onboard Jack Carrozzo to PC

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/productcom#10]
- [x] gmail [jackc@peeringdb.com](https://github.com/peeringdb/productcom/issues/jackc@peeringdb.com)
- [x]  Add to slack
- [x] add to productcom mailing list
- [x] add to PC page in PeeringDB slide deck
- [x] add to PC page on docs.peeringdb.com
- [x] add to PC github group (@jackcarrozzo)

**Comment by ccaputo** [comment]
- [x] gmail [jackc@peeringdb.com](https://github.com/peeringdb/productcom/issues/jackc@peeringdb.com)
- [x] add to productcom mailing list
- [x] add to PC github group (@jackcarrozzo)

@ghankins

**Comment by ghankins** [comment]
- [x]  Add to slack
- [x] add to PC page on docs.peeringdb.com

**Comment by jackcarrozzo** [comment]
@ccaputo could you please reset my gmail pwd or resend the invitation? Looks like I just missed the 48hr window :-(

**Comment by ccaputo** [comment]
> @ccaputo could you please reset my gmail pwd or resend the invitation? Looks like I just missed the 48hr window :-(

Done! :-)

**Comment by ghankins** [comment]
- [x] add to PC page in PeeringDB slide deck
