### ISSUE TITLE
Onboard Paul Hoogsteder to PC

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/productcom#12]
- [x] gmail paulh@peeringdb.com
- [x] Add to slack
- [x] add to productcom mailing list
- [x] add to PC page in PeeringDB slide deck
- [x] add to PC page on docs.peeringdb.com
- [x] add to PC github group (@paulhoogsteder)

**Comment by ccaputo** [comment]
- [x] gmail paulh@peeringdb.com
- [x] add to productcom mailing list
- [x] add to PC github group (@paulhoogsteder)

**Comment by ghankins** [comment]
- [x] Add to slack
- [ ] add to PC page in PeeringDB slide deck (email sent)
- [x] add to PC page on docs.peeringdb.com

**Comment by ghankins** [comment]
- [x] add to PC page in PeeringDB slide deck (email sent)
