### ISSUE TITLE
De-board Florian Hibler from PC

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/productcom#2]
[x] remove from productcom mailing list
[x] close peeringdb.com email address
[x] remove from peeringdb slack
[x] remove from productcom page in docs.peeringdb.com
[x] redistribute assigned issues
[x] remove from productcom page in PDB deck
[x] Remove from peeringdb github team
[o] award plaque sent

**Comment by ccaputo** [comment]
[x] remove from productcom mailing list
[x] close peeringdb.com email address
[x] remove from productcom page in docs.peeringdb.com

**Comment by ccaputo** [comment]
[x] Remove from peeringdb github team

**Comment by job** [comment]
[x] remove from peeringdb slack

**Comment by ghankins** [comment]
[x] remove from productcom page in PDB deck

**Comment by mcmanuss8** [comment]
Florian already has plaque

**Comment by arnoldnipper** [comment]
> Florian already has plaque

This plaque was for his work as AC member ...

**Comment by mcmanuss8** [comment]
ah I misunderstood Florian's email, thought he didn't want a 2nd one. asked Aaron to get him another :)
