### ISSUE TITLE
De-board Greg Villain

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/productcom#3]
[X] remove from productcom mailing list
[X] close peeringdb.com email address
[X] remove from peeringdb slack
[X] remove from productcom page in docs.peeringdb.com
[X] redistribute assigned issues
[X] remove from productcom page in PDB deck
[X] Remove from peeringdb github team
[ ] award plaque sent

**Comment by mcmanuss8** [comment]
@grizz can you help with mailing list?
@ghankins  can you help with slack, docs and dec?
I'll redistribute assigned issues, remove from github team, ask Aaron to send award plaque

**Comment by ccaputo** [comment]
[x] remove from productcom mailing list
[x] close peeringdb.com email address - Looks like someone else did this already.  Who?
[x] remove from productcom page in docs.peeringdb.com

**Comment by ccaputo** [comment]
> [x] close peeringdb.com email address - Looks like someone else did this already. Who?

From the audit log, @grizz did this on 5/28.  ;-)

**Comment by grizz** [comment]
I removed his email and the GitHub group, there's an email on the PC list with him requesting I do it. :)

**Comment by ghankins** [comment]
[X] remove from peeringdb slack
[X] remove from productcom page in PDB deck
