### ISSUE TITLE
De-board Shane Kerr from PC

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/productcom#4]
[x] remove from productcom mailing list
[x] close peeringdb.com email address
[x] remove from peeringdb slack
[x] remove from productcom page in docs.peeringdb.com
[none found] redistribute assigned issues
[x] remove from productcom page in PDB deck
[x] Remove from peeringdb github team and github org
[x] Remove user privileges (i.e. staff resp. superuser status)
[ ] award plaque sent

**Comment by ccaputo** [comment]
[x] remove from productcom mailing list
[x] close peeringdb.com email address
[x] remove from productcom page in docs.peeringdb.com
[none found] redistribute assigned issues
[x] Remove from peeringdb github team and github org

**Comment by ghankins** [comment]
[x] remove from peeringdb slack
 [x] remove from productcom page in PDB deck

**Comment by arnoldnipper** [comment]
@mcmanuss8, please add

 [ ] Remove user privileges (i.e. staff resp. superuser status)
 
 to your de-boarding list
