### ISSUE TITLE
Onboard Kayla Clifford

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/productcom#5]
[x] gmail kayla@peeringdb.com (see internal stewards mail for personal e-mail address)
[x] Add to slack
[x] add to productcom mailing list
[ ] add to PC page in PeeringDB slide deck
[x] add to PC page on docs.peeringdb.com
[x] add to PC github group (kaycliff)

**Comment by ghankins** [comment]
[x] add to PC page on docs.peeringdb.com

**Comment by ccaputo** [comment]
[x] gmail kayla@peeringdb.com (see internal stewards mail for personal e-mail address)
[x] add to productcom mailing list

**Comment by ghankins** [comment]
[x] Add to slack

Sent email asking for head shot.

**Comment by arnoldnipper** [comment]
[x] add to PC github group (kaycliff) (invitation sent)
