### ISSUE TITLE
Onboard Martin Hannigan

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/productcom#6]
[x] gmail mjh@peeringdb.com (see internal stewards mail for personal e-mail address)
[x] Add to slack
[x] add to productcom mailing list
[x] add to PC page in PeeringDB slide deck (ghankins request sent 2021-09-03)
[x] add to PC page on docs.peeringdb.com
[x] add to PC github group (@martinhannigan)

**Comment by ccaputo** [comment]
[x] gmail mjh@peeringdb.com [was marty@peeringdb.com briefly] (see internal stewards mail for personal e-mail address)
[x] add to PC page on docs.peeringdb.com
[x] add to PC github group (@martinhannigan)

**Comment by arnoldnipper** [comment]
> [x] gmail [marty@peeringdb.com](mailto:marty@peeringdb.com) (see internal stewards mail for personal e-mail address)

@ccaputo, you are aware that this email address was used by Marty Strong?

**Comment by ccaputo** [comment]
> > [x] gmail [marty@peeringdb.com](mailto:marty@peeringdb.com) (see internal stewards mail for personal e-mail address)
> 
> @ccaputo, you are aware that this email address was used by Marty Strong?

I didn't recall that.  Am following @mcmanuss8's directions so please reach out to him or Marty if I should do something else.

**Comment by arnoldnipper** [comment]
> I didn't recall that. Am following @mcmanuss8's directions so please reach out to him or Marty if I should do something else.

Maybe we should keep track of addresses used. I was trying to add Martin to slack, but couldn't as the this account is still on Marty Strong (though inactivated)

**Comment by mcmanuss8** [comment]
Ah I didn’t realize we had used it for other Marty. Let’s do hannigan@ ?

-Steve

**Comment by martinhannigan** [comment]
Works for me.

**Comment by martinhannigan** [comment]
Actually, mjh@ would be better since there are multiple collisions = Marty

Thanks again.

**Comment by ccaputo** [comment]
> Actually, mjh@ would be better since there are multiple collisions = Marty

Hey Marty, I have made this change.  mjh@peeringdb.com.  Thanks!

**Comment by arnoldnipper** [comment]
[x] Add to slack
 - invite sent to mjh@peeringdb.com

**Comment by ghankins** [comment]
[x] add to productcom mailing list
[ ] add to PC page in PeeringDB slide deck (ghankins request sent 2021-09-03)

**Comment by martinhannigan** [comment]
Access to the email or is it aliased to hannigan@ _or_ pointer towards
"internal stewards"? Thanks all. Excited to be lending a hand.

**Comment by ccaputo** [comment]
> Access to the email or is it aliased to hannigan@ _or_ pointer towards "internal stewards"? Thanks all. Excited to be lending a hand.

I reached out to @martinhannigan privately.

**Comment by martinhannigan** [comment]
Thanks. Im missing something probably simple re: @peeringdb.com email.  The
rest is done.

**Comment by ccaputo** [comment]
> Thanks. Im missing something probably simple re: @peeringdb.com email. The rest is done.

Are you seeing my direct non-GitHub emails?  Spam/junk folder?  Please email me at secretary@peeringdb.com.

**Comment by ghankins** [comment]
[x] add to PC page in PeeringDB slide deck
