### ISSUE TITLE
Onboard Peter Helmenstine to PC

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/productcom#7]
[x] Already has @peeringdb email
[x] Already on slack
[x] add to productcom mailing list
[x] add to PC page in PeeringDB slide deck
[x] add to PC page on docs.peeringdb.com
[x] add to PC github group (@peterhelmenstine)

**Comment by ccaputo** [comment]
[x] add to productcom mailing list
[x] add to PC page on docs.peeringdb.com
[x] add to PC github group (@peterhelmenstine)

**Comment by ghankins** [comment]
[x] add to PC page in PeeringDB slide deck
