### ISSUE TITLE
De-board Kayla Clifford

### ISSUE THREAD

**Issue by ghankins** [peeringdb/productcom#8]
- [x] deskpro
- [x] downgrade peeringdb user
- [x] remove from Slack
- [x] remove from productcom mailing list
- [x] close peeringdb.com email address
- [x] remove from product page in PDB deck
- [x] remove from product page on docs.peeringdb.com
- [x] reassign github issues
- [x] remove from peeringdb github team

Term 09/2021 - 03/2023

**Comment by ghankins** [comment]
- [x] remove from Slack
- [x] remove from productcom mailing list
- [x] remove from product page in PDB deck
- [x] remove from product page on docs.peeringdb.com

**Comment by ccaputo** [comment]
- [x] remove from productcom mailing list
- [x] close peeringdb.com email address
- [none found] reassign github issues
- [x] remove from peeringdb github team

**Comment by arnoldnipper** [comment]
- [0] deskpro
- [0] downgrade peeringdb user
