### ISSUE TITLE
Onboard Laurent Jarbinet

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/productcom#9]
- [x] gmail [laurent@peeringdb.com](laurent@peeringdb.com)
- [x] Add to slack
- [x] add to productcom mailing list
- [x] add to PC page in PeeringDB slide deck
- [x] add to PC page on docs.peeringdb.com
- [x] add to PC github group (@ljarbinet)

**Comment by ccaputo** [comment]
- [x] gmail [laurent@peeringdb.com](laurent@peeringdb.com)
- [x] add to productcom mailing list
- [x] add to PC github group (@ljarbinet)

**Comment by ghankins** [comment]
- [x] Add to slack

**Comment by ghankins** [comment]
- [x] add to PC page on docs.peeringdb.com

Asked for photo.

**Comment by ljarbinet** [comment]
> - [x] gmail [laurent@peeringdb.com](laurent@peeringdb.com)
> - [x] add to productcom mailing list
> - [x] add to PC github group (@ljarbinet)

Good morning,
For an obscure reason the googleApps invite ended up in my spam and I just found it but the 48h password reset link is not valid anymore
Do you mind re-generating it so I can complete my onboarding
Thanks
Laurent

**Comment by ccaputo** [comment]
> Good morning, For an obscure reason the googleApps invite ended up in my spam and I just found it but the 48h password reset link is not valid anymore Do you mind re-generating it so I can complete my onboarding Thanks Laurent

Done!

**Comment by ljarbinet** [comment]
Thanks Chris,
Link received and account activated!
Regards,
Laurent

Le mer. 10 mai 2023, 07:18, Chris Caputo ***@***.***> a
écrit :

**Comment by ghankins** [comment]
- [x] add to PC page in PeeringDB slide deck
